version: "3.8"

services:
  go-backend:
    build: .
    container_name: go-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
    driver: local
